### ISSUE TITLE
Not compatible with latest Spock core version

### ISSUE THREAD

**Issue by ghost** [anotherchrisberry/spock-retry#1]
My project uses Spock core 1.0-groovy-2.4
If I install spock-retry as is, 
I get 

```
groovy.lang.MissingPropertyException: No such property: cleanupMethod for class: org.spockframework.runtime.model.SpecInfo
Possible solutions: cleanupMethods
    at com.anotherchrisberry.spock.extensions.retry.RetryInterceptor.intercept(RetryInterceptor.groovy:26)
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

So I cloned and tried to change the dependency by myself. In that case it fails to build

**Comment by anotherchrisberry** [comment]
Hi, sorry for the late reply. I've been on vacation - hopefully I can get to this tomorrow. It should be pretty quick to fix.

**Comment by anotherchrisberry** [comment]
@mayur0612 can you give the code in this branch a shot and see if it works? https://github.com/anotherchrisberry/spock-retry/pull/2

**Comment by dpost** [comment]
@anotherchrisberry I'm still seeing the same error using 0.2-SNAPSHOT:

```
groovy.lang.MissingPropertyException: No such property: cleanupMethods for class: org.spockframework.runtime.model.SpecInfo
Possible solutions: cleanupMethod
    at com.anotherchrisberry.spock.extensions.retry.RetryInterceptor.intercept(RetryInterceptor.groovy:26)
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:84)
    at org.spockframework.runtime.extension.builtin.AbstractRuleInterceptor$1.evaluate(AbstractRuleInterceptor.java:37)
    at org.junit.rules.TestWatchman$1.evaluate(TestWatchman.java:48)
    at org.spockframework.runtime.extension.builtin.MethodRuleInterceptor.intercept(MethodRuleInterceptor.java:40)
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:84)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by anotherchrisberry** [comment]
Huh, I had no idea anybody actually used this thing!

@dpost Are you using Spock 0.7 or 1.0? It looks like the `RetryInterceptor` class changed; the 0.1-SNAPSHOT should still work with Spock 0.7, while the 0.2-SNAPSHOT version is targeting Spock 1.0.

**Comment by dpost** [comment]
Oops, my bad, I thought I had switched my dependencies to 1.0 but I must
have reverted them! It looks like your extension works now. Thank you

**Comment by ghost** [comment]
Thanks Chris! It builds now.

**Comment by anotherchrisberry** [comment]
Good to hear. I didn't actually test this (beyond running the specs) - let me know if you have any trouble, @mayur0612

**Comment by ghost** [comment]
@anotherchrisberry,
I did test this in my code. Works perfect!
