### ISSUE TITLE
java.lang.NoClassDefFoundError 

### ISSUE THREAD

**Issue by razmatazzz** [anotherchrisberry/spock-retry#25]
Any ideas how to fix the below error? I copied all the files [here](https://github.com/anotherchrisberry/spock-retry/tree/master/src/main/groovy/com/anotherchrisberry/spock/extensions/retry) into my project, but I sometimes get this error when running my tests:

```
java.lang.NoClassDefFoundError: cchproj/orea/park/apitests/utils/RetryInterceptor$_intercept_closure1

	at cchproj.orea.park.apitests.utils.RetryInterceptor.intercept(RetryInterceptor.groovy:41)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:88)
	at org.spockframework.runtime.extension.builtin.AbstractRuleInterceptor$1.evaluate(AbstractRuleInterceptor.java:37)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.spockframework.runtime.extension.builtin.TestRuleInterceptor.intercept(TestRuleInterceptor.java:38)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: cchproj.orea.park.apitests.utils.RetryInterceptor$_intercept_closure1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

```

**Comment by anotherchrisberry** [comment]
You need to import the annotation into your file, i.e.
```java
import com.anotherchrisberry.spock.extensions.retry.RetryInterceptor
```

**Comment by droidcodin** [comment]
not sure I understand. where do I put that import exactly? Do i put it in the class where I run my tests? I'm importing this already import `com.anotherchrisberry.spock.extensions.retry.RetryOnFailure` but why do I need that import?
